### ISSUE TITLE
Loading error - unterminated string meets end of file

### ISSUE THREAD

**Issue by thomthom** [thomthom/architect-tools#1]
**[Original report](https://bitbucket.org/thomthom/architect-tools/issue/1) by me.**

----------------------------------------

http://forums.sketchucation.com/viewtopic.php?f=323&t=30512#p306946

load 'tt_plan_tools.rb'
C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/tt_plan_tools.rb:34: warning: already initialized constant VERSION
C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/tt_plan_tools.rb:35: warning: already initialized constant PREF_KEY
Error: #<SyntaxError: (eval):35:in `read_default': (eval):35:in `read_default': compile error
(eval):35: unterminated string meets end of file>
(eval):2537
C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/TT_Lib2/settings.rb:48:in `[]'
C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/TT_Lib2/settings.rb:88:in `set_default'
C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/tt_plan_tools.rb:43
(eval):2537:in `load'
(eval):2537

**Comment by thomthom** [comment]
Unable to reproduce. User reports it working on secondary computer. Assume to be local problem to that specific machine.
